// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function SilentPrint(arg1) {
  return window['go']['main']['App']['SilentPrint'](arg1);
}
