// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate(arg1:string):Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallUpdate(arg1:string):Promise<void>;

export function SilentPrint(arg1:string):Promise<void>;
