// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCheckForUpdates() {
  return window['go']['main']['Updater']['AutoCheckForUpdates']();
}

export function CheckForUpdates() {
  return window['go']['main']['Updater']['CheckForUpdates']();
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['Updater']['DownloadUpdate'](arg1, arg2);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['Updater']['InstallUpdate'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['Updater']['Startup'](arg1);
}
