// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AutoCheckForUpdates():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateResult>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function InstallUpdate(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
